"" Highlight the screen line of the cursor with CursorLine
set cursorline

" Enable syntax highlighting 
if has('syntax')
        syntax enable
endif

set background=light
colorscheme solarized
set guifont=Liberation\ Mono\ 8,Consolas
set lines=75 columns=162
set guioptions-=T
"set guioptions-=m
set guioptions-=r
set guioptions-=L
set showtabline=2

map \gv :tabnew $MYGVIMRC<CR><C-W>
map <silent> \gV :source $MYGVIMRC<CR>:filetype detect<CR>:execute ":echo 'gvimrc reloaded'"<CR>
map \t :tabnew<CR>

set guicursor+=n:blinkon0

set visualbell t_vb=

