"" Highlight the screen line of the cursor with CursorLine
set cursorline

" Enable syntax highlighting 
if has('syntax')
        syntax enable
endif

set background=light
colorscheme solarized
set guifont=Liberation\ Mono\ 8,Ubuntu_Mono:h10:cANSI,Consolas:h10:cANSI
set lines=75 columns=162
set guioptions-=T
"set guioptions-=m
set guioptions-=r
set guioptions-=L

map \gv :tabnew $MYGVIMRC<CR><C-W>
map <silent> \gV :source $MYGVIMRC<CR>:filetype detect<CR>:execute ":echo 'gvimrc reloaded'"<CR>

set guicursor+=n:blinkon0

set visualbell t_vb=

if exists("+showtabline")
  function! MyTabLine()
    let s = ''
    let t = tabpagenr()
    let i = 1

    while i <= tabpagenr('$')
      let buflist = tabpagebuflist(i)
      let winnr = tabpagewinnr(i)
      let s .= '%' . i . 'T'
      let s .= (i == t ? '%1*' : '%2*')
      let s .= (i == t ? '%#TabLineSel#' : '%#TabLine#')
      let file = bufname(buflist[winnr - 1])
      let file = fnamemodify(file, ':p:t')
      let file = (file == '') ? '[No Name]' : file
      let s .= ' ' . file . ' '
      let s .= winnr
      let s .= (getbufvar(buflist[winnr - 1], '&modified') ? '+ ' : ' ')
      let i = i + 1
    endwhile
    let s .= '%T%#TabLineFill#%='
    let s .= (tabpagenr('$') > 1 ? '%999XX' : 'X')
    return s
  endfunction
  set showtabline=2
  set tabline=%!MyTabLine()
endif
