" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" 256 color
set t_Co=256

" Activate pathogen
call pathogen#infect()
call pathogen#helptags()

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

"" use indents of 4 spaces, and have them copied down lines:
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set smarttab
set expandtab

set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set showmatch           " highlight matching bracket
set nowrap              " don't break long lines
set autoread
set report=0            " report all changes
set scrolloff=4         " show some lines around the cursor

" Create swap files in this folders (in this order).
set directory=~/tmp,/var/tmp,/tmp,.
" But just don't create swap files.
set noswapfile

set wildmenu

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" Don't use Ex mode, use Q for formatting
map Q gq

" have syntax highlighting in terminals which can display colors:
if has('syntax') && (&t_Co > 2)
        syntax enable
        colorscheme zenburn2

        " TODO: This shouldn't go here, but in the autocommands section.
        " However, as I still don't know how to use them, I'll leave this
        " lines here for the moment.
        let c_gnu = 1
        let c_space_errors = 1

endif

"" have the mouse enabled all the time:
"if has('mouse')
"  set mouse=a
"  set ttymouse=xterm2
"endif

" Disable X clipboard support if DISPLAY is set, because it 
" greatly slows down console vim startup.
if ! has( "gui_running" )
    let g:display_num =
                \ substitute( $DISPLAY ,
                \ "^[[:alpha:]]*:\([[:digit:]]\+\)\.[[:digit:]]\+$" ,
                \ "\1" , "" )
    if ( g:display_num >= 0 )
        set clipboard=exclude:.*
    endif
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  " When using multiple windows, set a minimum width and height
  "autocmd GUIEnter *
  "  \ set winheight=60 winwidth=90 winminwidth=10 winminheight=10

  augroup END

  au BufNewFile,BufRead Master.make set filetype=make
  au BufNewFile,BufRead Master.hier set filetype=make

  :autocmd BufRead,BufNewFile *.cmake,CMakeLists.txt,*.cmake.in runtime! indent/cmake.vim
  :autocmd BufRead,BufNewFile *.cmake,CMakeLists.txt,*.cmake.in setf cmake
  :autocmd BufRead,BufNewFile *.ctest,*.ctest.in setf cmake

else
  " always set autoindenting on
  set autoindent
endif " has("autocmd")

"" make searches case-insensitive, unless they contain upper-case letters:
set ignorecase
set smartcase

"" use <Ctrl>+N/<Ctrl>+P to cycle through files:
nnoremap <C-N> :next<CR>
nnoremap <C-P> :prev<CR>
" [<Ctrl>+N by default is like j, and <Ctrl>+P like k.]

"" Show line numbers
set number

"" Always show the statusline
set laststatus=2

"" Highlight searched patterns
set hlsearch

"" Press Space to turn off highlighting and clear any messages already
"" displayeds
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

"" Estas tres lineas definen comandos ficticios para "Q", "W" y "Wq" que
"" equivalen respectivamente a "q", "w" y "wq".
command! -bang W write<bang>
command! -nargs=0 -bang Q q<bang>
command! -nargs=0 -bang Wq wq<bang>
command! -nargs=0 -bang Qa qa<bang>
command! -nargs=0 -bang Wqa wqa<bang>
command! -nargs=0 -bang WQa wqa<bang>

"" when using list, keep tabs at their full width and display `arrows':
" (Character 187 is a right double-chevron, and 183 a mid-dot.)
"execute 'set listchars+=tab:' . nr2char(187) . nr2char(183)
"set list
"set listchars=tab:>.

"" Pulsando "%" (es decir: Mayusculas-5) se puede saltar entre los pares de
"" corchetes, llaves y parentesis. Cargando "matchit" podemos usar esa misma
"" tecla para saltar entre los grupos de palabras "if else endif", "begin end"
"" y sentencias similares de cada lenguaje de programacion.
runtime! macros/matchit.vim

"" Shift-Tab cycles through tabs
nnoremap <S-tab> :tabnext<cr>
nnoremap <C-S-tab> :tabprevious<CR>

" Use Ctrl-\ to open a tag definition in a new tab.
map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>

"" Configuracion especifica para vimdiff o vim -d
if &diff 
  set nonumber 
  set diffopt=filler,iwhite

endif

"" Para que, al hacer diff dentro de Vi, el split sea vertical por defecto,
"" junto con las settings antes definidas
set diffopt=filler,iwhite,vertical

" When vertically splitting the window, make the new window appear on the right
set splitright

" When horizontally splitting the window, make the new window appear below
set splitbelow

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

" Ctrl-P: support for Perforce projects
"if exists("g:loaded_ctrlp")
    let g:ctrlp_root_markers = [ '.p4config' ]
"endif

" vim-signify: Set VCS systems. Also disable by default, so I can enable via
" :SignifyToggle/SignifyEnable
let g:signify_disable_by_default = 1
let g:signify_vcs_list = [ 'perforce', 'git' ]

