" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" Activate pathogen
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

"" use indents of 2 spaces, and have them copied down lines:
set tabstop=8
set softtabstop=2
set shiftwidth=2
set shiftround
set smarttab
set expandtab

set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set showmatch           " highlight matching bracket
set nowrap              " don't break long lines
set autoread
set report=0            " report all changes
set scrolloff=4         " show some lines around the cursor

" Create swap files in this folders (in this order).
set directory=~/tmp,/var/tmp,/tmp,.

set wildmenu
set wildmode=list,full


" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" Don't use Ex mode, use Q for formatting
map Q gq

" have syntax highlighting in terminals which can display colors:
if has('syntax') && (&t_Co > 2)
        syntax enable

        " TODO: This shouldn't go here, but in the autocommands section.
        " However, as I still don't know how to use them, I'll leave this
        " lines here for the moment.
        let c_gnu = 1
        let c_space_errors = 1
        let javascript_space_errors = 1

endif

"" have the mouse enabled all the time:
if has('mouse')
  set mouse=a
  set ttymouse=xterm2
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 79 characters.
  autocmd FileType text setlocal textwidth=79

  " For python files, indent using 4 spaces
  autocmd FileType python setlocal softtabstop=4 shiftwidth=4

  " Autoformat gitcommit files
  autocmd FileType gitcommit setlocal formatoptions+=ta

  autocmd FileType javascript
    \ setlocal softtabstop=4 shiftwidth=4 textwidth=79

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  " When using multiple windows, set a minimum width and height
  "autocmd GUIEnter *
  "  \ set winheight=60 winwidth=90 winminwidth=10 winminheight=10

  augroup END

else
  " always set autoindenting on
  set autoindent
endif " has("autocmd")

"" make searches case-insensitive, unless they contain upper-case letters:
set ignorecase
set smartcase

"" use <Ctrl>+N/<Ctrl>+P to cycle through files:
nnoremap <C-N> :next<CR>
nnoremap <C-P> :prev<CR>
" [<Ctrl>+N by default is like j, and <Ctrl>+P like k.]

"" Show line numbers
set number

"" Always show the statusline
set laststatus=2

"" have <Tab> (and <Shift>+<Tab> where it works) change the level of
"" indentation:
"inoremap <Tab> <C-T>
"inoremap <S-Tab> <C-D>
"" [<Ctrl>+V <Tab> still inserts an actual tab character.]

"" Highlight searched patterns
set hlsearch

"" Press Space to turn off highlighting and clear any messages already
"" displayeds
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

"" Estas tres lineas definen comandos ficticios para "Q", "W" y "Wq" que
"" equivalen respectivamente a "q", "w" y "wq".
command! -bang W write<bang>
command! -nargs=0 -bang Q q<bang>
command! -nargs=0 -bang Wq wq<bang>
command! -nargs=0 -bang Qa qa<bang>
command! -nargs=0 -bang Wqa wqa<bang>
command! -nargs=0 -bang WQa wqa<bang>

"" when using list, keep tabs at their full width and display `arrows':
" (Character 187 is a right double-chevron, and 183 a mid-dot.)
"execute 'set listchars+=tab:' . nr2char(187) . nr2char(183)
"set list
"set listchars=tab:>.

"" Pulsando "%" (es decir: Mayusculas-5) se puede saltar entre los pares de
"" corchetes, llaves y parentesis. Cargando "matchit" podemos usar esa misma
"" tecla para saltar entre los grupos de palabras "if else endif", "begin end"
"" y sentencias similares de cada lenguaje de programacion.
runtime! macros/matchit.vim

" Map \v to open a new tab and edit this .vimrc file. Use \V to load it.
map \v :tabnew $MYVIMRC<CR><C-W>
map <silent> \V :source $MYVIMRC<CR>:filetype detect<CR>:exe ":echo 'vimrc reloaded'"<CR>

" Use Alt-Shift-{ and Alt-Shift-} to move between tabs
map { :tabprevious<CR>
map } :tabnext<CR>



" Use Ctrl-\ to open a tag definition in a new tab.
map <C-\> :tab split<CR>:exec("tag ".expand("<cword>"))<CR>

" Map \d to insert the current date
if exists("*strftime")
  nnoremap \d "=strftime("%b %d, %Y")<CR>P
  inoremap \d <C-R>=strftime("%b %d, %Y")<CR>
endif

"" Configuracion especifica para vimdiff o vim -d
if &diff 
  set nonumber 
  set diffopt=filler,iwhite

endif

"" Para que, al hacer diff dentro de Vi, el split sea vertical por defecto,
"" junto con las settings antes definidas
set diffopt=filler,iwhite,vertical

" When vertically splitting the window, make the new window appear on the right
set splitright

" When horizontally splitting the window, make the new window appear below
set splitbelow

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

" Synopsys-specific tag files
if exists("$RVR")
  set tags+=$RVR/syn/mainsh/tags
  "set tags=$RVR_ICC/syn/icc_sh/tags
endif

